DPP schema and context reference
uncefact/spec-untp pull request #104
Opened 2024-06-04 14:37 UTC by nissimsan

1. Adds JSON schema corresponding to the latest DPP example
2. References the context added on https://github.com/uncefact/spec-untp/pull/102

2024-06-04 14:42 UTC, nissimsan commented
CI fails on a broken link to a file which is added as part of this same PR. So it should be safe to dismiss the check error. 

@kshychko, can I ask you to confirm, pls?

2024-06-11 12:57 UTC, kshychko requested changes

2024-06-11 12:57 UTC, kshychko commented on website/docs/specification/DigitalProductPassport.md
> +| 0.5.0       | 04-06-2024 | Raw (for review)             | `https://uncefact.github.io/spec-untp/untp-v1.jsonld`                          | [DPP schema](../../schema/untp-digital-product-passport.0.
@nissimsan, you are referencing to a file that doesn't exist in you PR
```suggestion
| 0.5.0       | 04-06-2024 | Raw (for review)             | `https://uncefact.github.io/spec-untp/untp-v1.jsonld`                          | [DPP schema](../../schema/untp-digital-product-passport-schema.0.5.0.json)      |
```

2024-06-12 07:43 UTC, nissimsan commented
@kshychko , thanks for your feedback! Should be all fixed now. Cheers

2024-06-13 08:29 UTC, kshychko approved these changes

2024-06-13 08:50 UTC, merged