Update TrustGraphs.md
uncefact/spec-untp pull request #119
Opened 2024-06-27 09:49 UTC by susanne-guth-orlowski

Added a first small section about trusted issuers list.

2024-06-27 10:43 UTC, Fak3 requested changes

2024-06-27 10:43 UTC, Fak3 commented on website/docs/design-patterns/TrustGraphs.md
> +When a GHG emissions VC holder presents their credential to a verifier, both parties use a digital wallet for this exchange. This software enables its owner to securely acquire, store, manage, and ve
From my experience, term "digital wallet" is very ambiguous, different people imply very different things by this. Furthermore, presentation and verification of a credential can perfectly be performed without a wallet, but by http api requests sequence. So I would suggest to reword this section saying that verifier software verifies, validates and checks authenticity.

2024-07-03 21:01 UTC, onthebreeze reviewed
The UNTP has been designed to avoid the need for wallets.  Can we discuss this one further please?

2024-07-03 21:20 UTC, onthebreeze reviewed
there is nothing ot prevent use of wallets (eg verifiers can fetch and store in a wallet) or holders can present from wallets.  But we prefer not to depend on wallets.

2024-07-22 09:51 UTC, philarcher commented
The text proposed is perfectly fine IMO, however, the term "recognized authority" perhaps needs considering. Recognized by whom? If we're talking individuals then, well, you trust who you trust. That's not an engineering task. But for UNTP, do we need to contemplate some sort of register of trusted parties? Such a register would, I imagine, cite the likes of ILAC and IAF as roots of trust, but that should not exclude others like the GBA or Rainforest Alliance.

Even then, it's not really enough. Sticking with CO2 emissions, if I have two different assessments of a product's CO2 footprint, one linked from the DPP and one I found elsewhere, and they differ, well, who's to say which one's right? Manufacturers will go to the GHG emission calculator that gives them the best result, whether it's true or not. An independent one might give an assessment that, as an individual, I might trust more. In the real world, it's likely that the independent assessment will be less favourable. 

Anything like a register of recognized authorities would be a big overhead and one we almost certainly want to avoid if at all possible but I fear it may be unavoidable.

2024-08-08 04:39 UTC, onthebreeze commented
modifed suzanne's text and created a new PR.  Therefore closing this one.

2024-08-08 04:39 UTC, closed without merging